<?php

namespace App\Http\Controllers;
use DB;
use Schema;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class WelcomeController extends Controller
{
    var $books = [
        1 => 'Genesis',
        2 => 'Exodus',
        3 => 'Leviticus',
        4 => 'Numbers',
        5 => 'Deuteronomy',
        6 => 'Joshua',
        7 => 'Judges',
        8 => 'Ruth',
        9 => '1 Samuel',
        10 => '2 Samuel',
        11 => '1 Kings',
        12 => '2 Kings',
        13 => '1 Chronicles',
        14 => '2 Chronicles',
        15 => 'Ezra',
        16 => 'Nehemiah',
        17 => 'Esther',
        18 => 'Job',
        19 => 'Psalm',
        20 => 'Proverbs',
        21 => 'Ecclesiastes',
        23 => 'Isaiah',
        24 => 'Jeremiah',
        25 => 'Lamentations',
        26 => 'Ezekiel',
        27 => 'Daniel',
        28 => 'Hosea',
        29 => 'Joel',
        30 => 'Amos',
        31 => 'Obadiah',
        32 => 'Jonah',
        33 => 'Micah',
        34 => 'Nahum',
        35 => 'Habakkuk',
        36 => 'Zephaniah',
        37 => 'Haggai',
        38 => 'Zechariah',
        39 => 'Malachi',
        40 => 'Matthew',
        41 => 'Mark',
        42 => 'Luke',
        43 => 'John',
        44 => 'Acts',
        45 => 'Romans',
        46 => '1 Corinthians',
        47 => '2 Corinthians',
        48 => 'Galatians',
        49 => 'Ephesians',
        50 => 'Philippians',
        51 => 'Colossians',
        52 => '1 Thessalonians',
        53 => '2 Thessalonians',
        54 => '1 Timothy',
        55 => '2 Timothy',
        56 => 'Titus',
        57 => 'Philemon',
        58 => 'Hebrews',
        59 => 'James',
        60 => '1 Peter',
        61 => '2 Peter',
        62 => '1 John',
        63 => '2 John',
        64 => '3 John',
        65 => 'Jude',
        66 => 'Revelation',
    ];

    var $versions = [
        12 => "American Standard Version (ASV)",
        8 => "Amplified Bible, Classic Edition (AMPC)",
        42 => "Catholic Public Domain Version (CPDV)",
        1713 => "Christian Standard Bible (CSB)",
        37 => "Common English Bible (CEB)",
        1275 => "Complete Jewish Bible (CJB)",
        294 => "Contemporary English Version (Anglicised) 2012 (CEVUK)",
        392 => "Contemporary English Version (CEV)",
        303 => "Contemporary English Version (CEVDC)",
        478 => "Darby's Translation 1890 (DARBY)",
        55 => "Douay-Rheims Challoner Revision 1752 (DRC1752)",
        2079 => "EasyEnglish Bible 2018 (EASY)",
        59 => "English Standard Version (ESV)",
        1932 => "Free Bible Version New Testament with Psalms (FBVNTPSALMS)",
        70 => "GOD'S WORD Translation (GW)",
        416 => "Good News Bible (Anglicised) (GNBDC)",
        431 => "Good News Bible (Catholic edition in Septuagint order) (GNBDK)",
        296 => "Good News Bible (GNB)",
        68 => "Good News Translation (GNT)",
        69 => "Good News Translation (US Version) (GNTD)",
        72 => "Holman Christian Standard Bible (HCSB)",
        406 => "Holy Bible: Easy-to-Read Version (ERV)",
        1359 => "International Children’s Bible (ICB)",
        1077 => "Jubilee Bible (JUB)",
        1 => "King James Version (KJV)",
        547 => "King James Version with Apocrypha, American Edition (KJVA)",
        90 => "Lexham English Bible (LEB)",
        1365 => "Metrical Psalms 1650 (MP1650)",
        1171 => "Modern English Version (MEV)",
        463 => "New American Bible, revised edition (NABRE)",
        100 => "New American Standard Bible (NASB)",
        105 => "New Century Version (NCV)",
        107 => "New English Translation (NET)",
        113 => "New International Version (Anglicised) (NIVUK)",
        114 => "New King James Version (NKJV)",
        116 => "New Living Translation (NLT)",
        2135 => "New Messianic Version Bible (NMV)",
        2016 => "New Revised Standard Version (NRSV)",
        130 => "Orthodox Jewish Bible (OJB)",
        2020 => "Revised Standard Version (RSV)",
        477 => "Revised Version 1885 (RV1885)",
        1922 => "Revised Version with Apocrypha 1895 (RV1895)",
        1047 => "St Paul from the Trenches 1916 (GWC)",
        1588 => "The Amplified Bible (AMP)",
        31 => "The Books of the Bible NT (BOOKS)",
        97 => "The Message (MSG)",
        1849 => "The Passion Translation (TPT)",
        316 => "The Scriptures 2009 (TS2009)",
        314 => "Tree of Life Version (TLV)",
        206 => "World English Bible (WEB)",
        1204 => "World English Bible British Edition (WEBBE)",
        1209 => "World Messianic Bible (WMB)",
        1207 => "World Messianic Bible British Edition (WMBBE)",
        821 => "Young's Literal Translation 3rd Revision 1898 (YLT1898)",
    ];

    var $versionIdsToTable = [
        821 => "t_ylt1898",
        1207 => "t_wmbbe",
        1209 => "t_wmb",
        1204 => "t_webbe",
        206 => "t_web",
        316 => "t_ts2009",
        1849 => "t_tpt",
        314 => "t_tlv",
        1922 => "t_rv1895",
        477 => "t_rv1885",
        2020 => "t_rsv",
        130 => "t_ojb",
        2016 => "t_nrsv",
        2135 => "t_nmv",
        116 => "t_nlt",
        114 => "t_nkjv",
        113 => "t_nivuk",
        107 => "t_net",
        105 => "t_ncv",
        100 => "t_nasb",
        463 => "t_nabre",
        97 => "t_msg",
        1365 => "t_mp1650",
        1171 => "t_mev",
        90 => "t_leb",
        547 => "t_kjva",
        1 => "t_kjv",
        1077 => "t_jub",
        1359 => "t_icb",
        72 => "t_hcsb",
        1047 => "t_gwc",
        70 => "t_gw",
        69 => "t_gntd",
        68 => "t_gnt",
        431 => "t_gnbdk",
        416 => "t_gnbdc",
        296 => "t_gnb",
        1932 => "t_fbvntpsalms",
        59 => "t_esv",
        406 => "t_erv",
        2079 => "t_easy",
        55 => "t_drc1752",
        478 => "t_darby",
        1713 => "t_csb",
        42 => "t_cpdv",
        1275 => "t_cjb",
        294 => "t_cevuk",
        303 => "t_cevdc",
        392 => "t_cev",
        37 => "t_ceb",
        31 => "t_books",
        12 => "t_asv",
        8 => "t_ampc",
        1588 => "t_amp",
    ];
    
    var $chapters = [
        "Genesis" => "GEN",
        "Exodus" => "EXO",
        "Leviticus" => "LEV",
        "Numbers" => "NUM",
        "Deuteronomy" => "DEU",
        "Joshua" => "JOS",
        "Judges" => "JDG",
        "Ruth" => "RUT",
        "1 Samuel" => "1SA",
        "2 Samuel" => "2SA",
        "1 Kings" => "1KI",
        "2 Kings" => "2KI",
        "1 Chronicles" => "1CH",
        "2 Chronicles" => "2CH",
        "Ezra" => "EZR",
        "Nehemiah" => "NEH",
        "Esther" => "EST",
        "Job" => "JOB",
        "Psalm" => "PSA",
        "Proverbs" => "PRO",
        "Ecclesiastes" => "ECC",
        "Song of Songs" => "SNG",
        "Isaiah" => "ISA",
        "Jeremiah" => "JER",
        "Lamentations" => "LAM",
        "Ezekiel" => "EZK",
        "Daniel" => "DAN",
        "Hosea" => "HOS",
        "Joel" => "JOL",
        "Amos" => "AMO",
        "Obadiah" => "OBA",
        "Jonah" => "JON",
        "Micah" => "MIC",
        "Nahum" => "NAM",
        "Habakkuk" => "HAB",
        "Zephaniah" => "ZEP",
        "Haggai" => "HAG",
        "Zechariah" => "ZEC",
        "Malachi" => "MAL",
        "Matthew" => "MAT",
        "Mark" => "MRK",
        "Luke" => "LUK",
        "John" => "JHN",
        "Acts" => "ACT",
        "Romans" => "ROM",
        "1 Corinthians" => "1CO",
        "2 Corinthians" => "2CO",
        "Galatians" => "GAL",
        "Ephesians" => "EPH",
        "Philippians" => "PHP",
        "Colossians" => "COL",
        "1 Thessalonians" => "1TH",
        "2 Thessalonians" => "2TH",
        "1 Timothy" => "1TI",
        "2 Timothy" => "2TI",
        "Titus" => "TIT",
        "Philemon" => "PHM",
        "Hebrews" => "HEB",
        "James" => "JAS",
        "1 Peter" => "1PE",
        "2 Peter" => "2PE",
        "1 John" => "1JN",
        "2 John" => "2JN",
        "3 John" => "3JN",
        "Jude" => "JUD",
        "Revelation" => "REV"
    ];

    var $booksByAbbr = [
        'GEN' => [ 'human' => 'Genesis', 'short' => 'GEN', 'bookId' => 1, 'g' => 1, ],
        'EXO' => [ 'human' => 'Exodus', 'short' => 'EXO', 'bookId' => 2, 'g' => 1, ],
        'LEV' => [ 'human' => 'Leviticus', 'short' => 'LEV', 'bookId' => 3, 'g' => 1, ],
        'NUM' => [ 'human' => 'Numbers', 'short' => 'NUM', 'bookId' => 4, 'g' => 1, ],
        'DEU' => [ 'human' => 'Deuteronomy', 'short' => 'DEU', 'bookId' => 5, 'g' => 1, ],
        'JOS' => [ 'human' => 'Joshua', 'short' => 'JOS', 'bookId' => 6, 'g' => 2, ],
        'JDG' => [ 'human' => 'Judges', 'short' => 'JDG', 'bookId' => 7, 'g' => 2, ],
        'RUT' => [ 'human' => 'Ruth', 'short' => 'RUT', 'bookId' => 8, 'g' => 2, ],
        '1SA' => [ 'human' => '1 Samuel', 'short' => '1SA', 'bookId' => 9, 'g' => 2, ],
        '2SA' => [ 'human' => '2 Samuel', 'short' => '2SA', 'bookId' => 10, 'g' => 2, ],
        '1KI' => [ 'human' => '1 Kings', 'short' => '1KI', 'bookId' => 11, 'g' => 2, ],
        '2KI' => [ 'human' => '2 Kings', 'short' => '2KI', 'bookId' => 12, 'g' => 2, ],
        '1CH' => [ 'human' => '1 Chronicles', 'short' => '1CH', 'bookId' => 13, 'g' => 2, ],
        '2CH' => [ 'human' => '2 Chronicles', 'short' => '2CH', 'bookId' => 14, 'g' => 2, ],
        'EZR' => [ 'human' => 'Ezra', 'short' => 'EZR', 'bookId' => 15, 'g' => 2, ],
        'NEH' => [ 'human' => 'Nehemiah', 'short' => 'NEH', 'bookId' => 16, 'g' => 2, ],
        'EST' => [ 'human' => 'Esther', 'short' => 'EST', 'bookId' => 17, 'g' => 2, ],
        'JOB' => [ 'human' => 'Job', 'short' => 'JOB', 'bookId' => 18, 'g' => 3, ],
        'undefined' => [ 'human' => 'Song of Solomon', 'bookId' => 22, 'g' => 3, ], 
        'PRO' => [ 'human' => 'Proverbs', 'short' => 'PRO', 'bookId' => 20, 'g' => 3, ],
        'ECC' => [ 'human' => 'Ecclesiastes', 'short' => 'ECC', 'bookId' => 21, 'g' => 3, ],
        'ISA' => [ 'human' => 'Isaiah', 'short' => 'ISA', 'bookId' => 23, 'g' => 4, ],
        'JER' => [ 'human' => 'Jeremiah', 'short' => 'JER', 'bookId' => 24, 'g' => 4, ],
        'LAM' => [ 'human' => 'Lamentations', 'short' => 'LAM', 'bookId' => 25, 'g' => 4, ],
        'EZK' => [ 'human' => 'Ezekiel', 'short' => 'EZK', 'bookId' => 26, 'g' => 4, ],
        'DAN' => [ 'human' => 'Daniel', 'short' => 'DAN', 'bookId' => 27, 'g' => 4, ],
        'HOS' => [ 'human' => 'Hosea', 'short' => 'HOS', 'bookId' => 28, 'g' => 4, ],
        'JOL' => [ 'human' => 'Joel', 'short' => 'JOL', 'bookId' => 29, 'g' => 4, ],
        'AMO' => [ 'human' => 'Amos', 'short' => 'AMO', 'bookId' => 30, 'g' => 4, ],
        'OBA' => [ 'human' => 'Obadiah', 'short' => 'OBA', 'bookId' => 31, 'g' => 4, ],
        'JON' => [ 'human' => 'Jonah', 'short' => 'JON', 'bookId' => 32, 'g' => 4, ],
        'MIC' => [ 'human' => 'Micah', 'short' => 'MIC', 'bookId' => 33, 'g' => 4, ],
        'NAM' => [ 'human' => 'Nahum', 'short' => 'NAM', 'bookId' => 34, 'g' => 4, ],
        'HAB' => [ 'human' => 'Habakkuk', 'short' => 'HAB', 'bookId' => 35, 'g' => 4, ],
        'ZEP' => [ 'human' => 'Zephaniah', 'short' => 'ZEP', 'bookId' => 36, 'g' => 4, ],
        'HAG' => [ 'human' => 'Haggai', 'short' => 'HAG', 'bookId' => 37, 'g' => 4, ],
        'ZEC' => [ 'human' => 'Zechariah', 'short' => 'ZEC', 'bookId' => 38, 'g' => 4, ],
        'MAL' => [ 'human' => 'Malachi', 'short' => 'MAL', 'bookId' => 39, 'g' => 4, ],
        'MAT' => [ 'human' => 'Matthew', 'short' => 'MAT', 'bookId' => 40, 'g' => 5, ],
        'MRK' => [ 'human' => 'Mark', 'short' => 'MRK', 'bookId' => 41, 'g' => 5, ],
        'LUK' => [ 'human' => 'Luke', 'short' => 'LUK', 'bookId' => 42, 'g' => 5, ],
        'JHN' => [ 'human' => 'John', 'short' => 'JHN', 'bookId' => 43, 'g' => 5, ],
        'ACT' => [ 'human' => 'Acts', 'short' => 'ACT', 'bookId' => 44, 'g' => 6, ],
        'ROM' => [ 'human' => 'Romans', 'short' => 'ROM', 'bookId' => 45, 'g' => 7, ],
        '1CO' => [ 'human' => '1 Corinthians', 'short' => '1CO', 'bookId' => 46, 'g' => 7, ],
        '2CO' => [ 'human' => '2 Corinthians', 'short' => '2CO', 'bookId' => 47, 'g' => 7, ],
        'GAL' => [ 'human' => 'Galatians', 'short' => 'GAL', 'bookId' => 48, 'g' => 7, ],
        'EPH' => [ 'human' => 'Ephesians', 'short' => 'EPH', 'bookId' => 49, 'g' => 7, ],
        'PHP' => [ 'human' => 'Philippians', 'short' => 'PHP', 'bookId' => 50, 'g' => 7, ],
        'COL' => [ 'human' => 'Colossians', 'short' => 'COL', 'bookId' => 51, 'g' => 7, ],
        '1TH' => [ 'human' => '1 Thessalonians', 'short' => '1TH', 'bookId' => 52, 'g' => 7, ],
        '2TH' => [ 'human' => '2 Thessalonians', 'short' => '2TH', 'bookId' => 53, 'g' => 7, ],
        '1TI' => [ 'human' => '1 Timothy', 'short' => '1TI', 'bookId' => 54, 'g' => 7, ],
        '2TI' => [ 'human' => '2 Timothy', 'short' => '2TI', 'bookId' => 55, 'g' => 7, ],
        'TIT' => [ 'human' => 'Titus', 'short' => 'TIT', 'bookId' => 56, 'g' => 7, ],
        'PHM' => [ 'human' => 'Philemon', 'short' => 'PHM', 'bookId' => 57, 'g' => 7, ],
        'HEB' => [ 'human' => 'Hebrews', 'short' => 'HEB', 'bookId' => 58, 'g' => 7, ],
        'JAS' => [ 'human' => 'James', 'short' => 'JAS', 'bookId' => 59, 'g' => 7, ],
        '1PE' => [ 'human' => '1 Peter', 'short' => '1PE', 'bookId' => 60, 'g' => 7, ],
        '2PE' => [ 'human' => '2 Peter', 'short' => '2PE', 'bookId' => 61, 'g' => 7, ],
        '1JN' => [ 'human' => '1 John', 'short' => '1JN', 'bookId' => 62, 'g' => 7, ],
        '2JN' => [ 'human' => '2 John', 'short' => '2JN', 'bookId' => 63, 'g' => 7, ],
        '3JN' => [ 'human' => '3 John', 'short' => '3JN', 'bookId' => 64, 'g' => 7, ],
        'JUD' => [ 'human' => 'Jude', 'short' => 'JUD', 'bookId' => 65, 'g' => 7, ],
        'REV' => [ 'human' => 'Revelation', 'short' => 'REV', 'bookId' => 66, 'g' => 8, ],
        'PSA' => [ 'human' => 'PSALMS', 'short' => 'PSA', 'bookId' => 19, ] 
    ];
    var $versionFromIds = [
        1 => "kjv",
        8 => "AMPC",
        12 => "ASV",
        31 => "books",
        37 => "ceb",
        42 => "cpdv",
        55 => "DRC1752",
        59 => "ESV",
        68 => "GNT",
        69 => "GNTD",
        70 => "gw",
        72 => "hcsb",
        90 => "leb",
        97 => "msg",
        100 => "NASB",
        105 => "ncv",
        107 => "net",
        110 => "nirv-eng",
        111 => "NIV11",
        113 => "NIVUK",
        114 => "nkjv",
        116 => "nlt",
        130 => "ojb",
        206 => "web",
        294 => "CEVUK",
        296 => "GNB",
        303 => "CEVDC",
        314 => "TLV",
        316 => "TS2009",
        392 => "CEV",
        406 => "ERV",
        416 => "GNBDC",
        431 => "GNBDK",
        463 => "NABRE",
        477 => "RV1885",
        478 => "DARBY",
        547 => "KJVA",
        821 => "YLT1898",
        1047 => "GWC",
        1077 => "jub",
        1171 => "mev",
        1204 => "WEBBE",
        1207 => "WMBBE",
        1209 => "WMB",
        1275 => "CJB",
        1359 => "ICB",
        1365 => "MP1650",
        1588 => "AMP",
        1713 => "CSB",
        1849 => "TPT",
        1922 => "RV1895",
        1932 => "FBVNTPsalms",
        2015 => "NRSVCI",
        2016 => "NRSV",
        2017 => "RSVCI",
        2020 => "RSV",
        2079 => "EASY",
        2135 => "NMV",
        2163 => "enggnv"
    ];

    var $versionsToIds = [
        "kjv" => 1,
        "ampc" => 8,
        "asv" => 12,
        "books" => 31,
        "ceb" => 37,
        "cpdv" => 42,
        "drc1752" => 55,
        "esv" => 59,
        "gnt" => 68,
        "gntd" => 69,
        "gw" => 70,
        "hcsb" => 72,
        "leb" => 90,
        "msg" => 97,
        "nasb" => 100,
        "ncv" => 105,
        "net" => 107,
        "nirv-eng" => 110,
        "niv11" => 111,
        "nivuk" => 113,
        "nkjv" => 114,
        "nlt" => 116,
        "ojb" => 130,
        "web" => 206,
        "cevuk" => 294,
        "gnb" => 296,
        "cevdc" => 303,
        "tlv" => 314,
        "ts2009" => 316,
        "cev" => 392,
        "erv" => 406,
        "gnbdc" => 416,
        "gnbdk" => 431,
        "nabre" => 463,
        "rv1885" => 477,
        "darby" => 478,
        "kjva" => 547,
        "ylt1898" => 821,
        "gwc" => 1047,
        "jub" => 1077,
        "mev" => 1171,
        "webbe" => 1204,
        "wmbbe" => 1207,
        "wmb" => 1209,
        "cjb" => 1275,
        "icb" => 1359,
        "mp1650" => 1365,
        "amp" => 1588,
        "csb" => 1713,
        "tpt" => 1849,
        "rv1895" => 1922,
        "fbvntpsalms" => 1932,
        "nrsvci" => 2015,
        "nrsv" => 2016,
        "rsvci" => 2017,
        "rsv" => 2020,
        "easy" => 2079,
        "nmv" => 2135,
        "enggnv" => 2163
    ];

    var $tablesToCreate = [
        0 => [
            'table' => 't_ylt1898',
            'abbreviation' => 'YLT1898',
            'language' => 'english',
            'info_text' => 'Young\'s Literal Translation 3rd Revision 1898 (YLT1898)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/821-ylt1898-youngs-literal-translation-3rd-revision-1898',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/821/jhn.1.ylt1898',
        ],
        1 => [
            'table' => 't_wmbbe',
            'abbreviation' => 'WMBBE',
            'language' => 'english',
            'info_text' => 'World Messianic Bible British Edition (WMBBE)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1207-wmbbe-world-messianic-bible-british-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1207/jhn.1.wmbbe',
        ],
        2 => [
            'table' => 't_wmb',
            'abbreviation' => 'WMB',
            'language' => 'english',
            'info_text' => 'World Messianic Bible (WMB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1209-wmb-world-messianic-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1209/jhn.1.wmb',
        ],
        3 => [
            'table' => 't_webbe',
            'abbreviation' => 'WEBBE',
            'language' => 'english',
            'info_text' => 'World English Bible British Edition (WEBBE)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1204-webbe-world-english-bible-british-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1204/jhn.1.webbe',
        ],
        4 => [
            'table' => 't_web',
            'abbreviation' => 'WEB',
            'language' => 'english',
            'info_text' => 'World English Bible (WEB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/206-web-world-english-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/206/jhn.1.web',
        ],
        5 => [
            'table' => 't_ts2009',
            'abbreviation' => 'TS2009',
            'language' => 'english',
            'info_text' => 'The Scriptures 2009 (TS2009)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/316-ts2009-the-scriptures-2009',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/316/jhn.1.ts2009',
        ],
        6 => [
            'table' => 't_tpt',
            'abbreviation' => 'TPT',
            'language' => 'english',
            'info_text' => 'The Passion Translation (TPT)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1849-tpt-the-passion-translation',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1849/jhn.1.tpt',
        ],
        7 => [
            'table' => 't_tlv',
            'abbreviation' => 'TLV',
            'language' => 'english',
            'info_text' => 'Tree of Life Version (TLV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/314-tlv-tree-of-life-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/314/jhn.1.tlv',
        ],
        8 => [
            'table' => 't_rv1895',
            'abbreviation' => 'RV1895',
            'language' => 'english',
            'info_text' => 'Revised Version with Apocrypha 1895 (RV1895)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1922-rv1895-revised-version-with-apocrypha-1895',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1922/jhn.1.rv1895',
        ],
        9 => [
            'table' => 't_rv1885',
            'abbreviation' => 'RV1885',
            'language' => 'english',
            'info_text' => 'Revised Version 1885 (RV1885)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/477-rv1885-revised-version-1885',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/477/jhn.1.rv1885',
        ],
        10 => [
            'table' => 't_rsvci',
            'abbreviation' => 'RSV-CI',
            'language' => 'english',
            'info_text' => 'Revised Standard Version (RSV-CI)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2017-rsv-ci-revised-standard-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2017/jhn.1.rsv-ci',
        ],
        11 => [
            'table' => 't_rsv',
            'abbreviation' => 'RSV',
            'language' => 'english',
            'info_text' => 'Revised Standard Version (RSV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2020-rsv-revised-standard-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2020/jhn.1.rsv',
        ],
        12 => [
            'table' => 't_ojb',
            'abbreviation' => 'OJB',
            'language' => 'english',
            'info_text' => 'Orthodox Jewish Bible (OJB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/130-ojb-orthodox-jewish-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/130/jhn.1.ojb',
        ],
        13 => [
            'table' => 't_nrsvci',
            'abbreviation' => 'NRSV-CI',
            'language' => 'english',
            'info_text' => 'New Revised Standard Version Catholic Interconfessional (NRSV-CI)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2015-nrsv-ci-new-revised-standard-version-catholic-interconfessional',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2015/jhn.1.nrsv-ci',
        ],
        14 => [
            'table' => 't_nrsv',
            'abbreviation' => 'NRSV',
            'language' => 'english',
            'info_text' => 'New Revised Standard Version (NRSV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2016-nrsv-new-revised-standard-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2016/jhn.1.nrsv',
        ],
        15 => [
            'table' => 't_nmv',
            'abbreviation' => 'NMV',
            'language' => 'english',
            'info_text' => 'New Messianic Version Bible (NMV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2135-nmv-new-messianic-version-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2135/jhn.1.nmv',
        ],
        16 => [
            'table' => 't_nlt',
            'abbreviation' => 'NLT',
            'language' => 'english',
            'info_text' => 'New Living Translation (NLT)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/116-nlt-new-living-translation',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/116/jhn.1.nlt',
        ],
        17 => [
            'table' => 't_nkjv',
            'abbreviation' => 'NKJV',
            'language' => 'english',
            'info_text' => 'New King James Version (NKJV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/114-nkjv-new-king-james-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/114/jhn.1.nkjv',
        ],
        18 => [
            'table' => 't_nivuk',
            'abbreviation' => 'NIVUK',
            'language' => 'english',
            'info_text' => 'New International Version (Anglicised) (NIVUK)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/113-nivuk-new-international-version-anglicised',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/113/jhn.1.nivuk',
        ],
        19 => [
            'table' => 't_niv',
            'abbreviation' => 'NIV',
            'language' => 'english',
            'info_text' => 'New International Version (NIV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/111-niv-new-international-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/111/jhn.1.niv',
        ],
        20 => [
            'table' => 't_nirv',
            'abbreviation' => 'NIRV',
            'language' => 'english',
            'info_text' => 'New International Reader\'s Version (NIRV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/110-nirv-new-international-readers-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/110/jhn.1.nirv',
        ],
        21 => [
            'table' => 't_net',
            'abbreviation' => 'NET',
            'language' => 'english',
            'info_text' => 'New English Translation (NET)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/107-net-new-english-translation',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/107/jhn.1.net',
        ],
        22 => [
            'table' => 't_ncv',
            'abbreviation' => 'NCV',
            'language' => 'english',
            'info_text' => 'New Century Version (NCV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/105-ncv-new-century-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/105/jhn.1.ncv',
        ],
        23 => [
            'table' => 't_nasb',
            'abbreviation' => 'NASB',
            'language' => 'english',
            'info_text' => 'New American Standard Bible (NASB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/100-nasb-new-american-standard-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/100/jhn.1.nasb',
        ],
        24 => [
            'table' => 't_nabre',
            'abbreviation' => 'NABRE',
            'language' => 'english',
            'info_text' => 'New American Bible, revised edition (NABRE)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/463-nabre-new-american-bible-revised-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/463/jhn.1.nabre',
        ],
        25 => [
            'table' => 't_msg',
            'abbreviation' => 'MSG',
            'language' => 'english',
            'info_text' => 'The Message (MSG)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/97-msg-the-message',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/97/jhn.1.msg',
        ],
        26 => [
            'table' => 't_mp1650',
            'abbreviation' => 'MP1650',
            'language' => 'english',
            'info_text' => 'Metrical Psalms 1650 (MP1650)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1365-mp1650-metrical-psalms-1650',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1365/PSA.1.MP1650',
        ],
        27 => [
            'table' => 't_mev',
            'abbreviation' => 'MEV',
            'language' => 'english',
            'info_text' => 'Modern English Version (MEV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1171-mev-modern-english-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1171/jhn.1.mev',
        ],
        28 => [
            'table' => 't_leb',
            'abbreviation' => 'LEB',
            'language' => 'english',
            'info_text' => 'Lexham English Bible (LEB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/90-leb-lexham-english-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/90/jhn.1.leb',
        ],
        29 => [
            'table' => 't_kjva',
            'abbreviation' => 'KJVA',
            'language' => 'english',
            'info_text' => 'King James Version, American Edition (KJVA)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/547-kjva-king-james-version-american-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/547/jhn.1.kjva',
        ],
        30 => [
            'table' => 't_kjva',
            'abbreviation' => 'KJVA',
            'language' => 'english',
            'info_text' => 'King James Version with Apocrypha, American Edition (KJVA)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/546-kjva-king-james-version-with-apocrypha-american-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/546/jhn.1.kjva',
        ],
        31 => [
            'table' => 't_kjv',
            'abbreviation' => 'KJV',
            'language' => 'english',
            'info_text' => 'King James Version (KJV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1-kjv-king-james-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1/jhn.1.kjv',
        ],
        32 => [
            'table' => 't_jub',
            'abbreviation' => 'JUB',
            'language' => 'english',
            'info_text' => 'Jubilee Bible (JUB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1077-jub-jubilee-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1077/jhn.1.jub',
        ],
        33 => [
            'table' => 't_icb',
            'abbreviation' => 'ICB',
            'language' => 'english',
            'info_text' => 'International Children’s Bible (ICB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1359-icb-international-childrens-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1359/jhn.1.icb',
        ],
        34 => [
            'table' => 't_hcsb',
            'abbreviation' => 'HCSB',
            'language' => 'english',
            'info_text' => 'Holman Christian Standard Bible (HCSB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/72-hcsb-holman-christian-standard-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/72/jhn.1.hcsb',
        ],
        35 => [
            'table' => 't_gwc',
            'abbreviation' => 'GWC',
            'language' => 'english',
            'info_text' => 'St Paul from the Trenches 1916 (GWC)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1047-gwc-st-paul-from-the-trenches-1916',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1047/jhn.1.gwc',
        ],
        36 => [
            'table' => 't_gw',
            'abbreviation' => 'GW',
            'language' => 'english',
            'info_text' => 'GOD\'S WORD Translation (GW)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/70-gw-gods-word-translation',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/70/jhn.1.gw',
        ],
        37 => [
            'table' => 't_gnv',
            'abbreviation' => 'GNV',
            'language' => 'english',
            'info_text' => 'Geneva Bible (GNV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2163-gnv-geneva-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2163/jhn.1.gnv',
        ],
        38 => [
            'table' => 't_gntd',
            'abbreviation' => 'GNTD',
            'language' => 'english',
            'info_text' => 'Good News Translation (US Version) (GNTD)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/69-gntd-good-news-translation-us-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/69/jhn.1.gntd',
        ],
        39 => [
            'table' => 't_gnt',
            'abbreviation' => 'GNT',
            'language' => 'english',
            'info_text' => 'Good News Translation (GNT)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/68-gnt-good-news-translation',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/68/jhn.1.gnt',
        ],
        40 => [
            'table' => 't_gnbdk',
            'abbreviation' => 'GNBDK',
            'language' => 'english',
            'info_text' => 'Good News Bible (Catholic edition in Septuagint order) (GNBDK)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/431-gnbdk-good-news-bible-catholic-edition-in-septuagint-order',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/431/jhn.1.gnbdk',
        ],
        41 => [
            'table' => 't_gnbdc',
            'abbreviation' => 'GNBDC',
            'language' => 'english',
            'info_text' => 'Good News Bible (Anglicised) (GNBDC)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/416-gnbdc-good-news-bible-anglicised',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/416/jhn.1.gnbdc',
        ],
        42 => [
            'table' => 't_gnb',
            'abbreviation' => 'GNB',
            'language' => 'english',
            'info_text' => 'Good News Bible (GNB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/296-gnb-good-news-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/296/jhn.1.gnb',
        ],
        43 => [
            'table' => 't_fbvntpsalms',
            'abbreviation' => 'FBVNTPSALMS',
            'language' => 'english',
            'info_text' => 'Free Bible Version New Testament with Psalms (FBVNTPSALMS)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1932-fbvntpsalms-free-bible-version-new-testament-with-psalms',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1932/jhn.1.fbvntpsalms',
        ],
        44 => [
            'table' => 't_esv',
            'abbreviation' => 'ESV',
            'language' => 'english',
            'info_text' => 'English Standard Version (ESV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/59-esv-english-standard-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/59/jhn.1.esv',
        ],
        45 => [
            'table' => 't_erv',
            'abbreviation' => 'ERV',
            'language' => 'english',
            'info_text' => 'Holy Bible: Easy-to-Read Version (ERV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/406-erv-holy-bible-easy-to-read-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/406/jhn.1.erv',
        ],
        46 => [
            'table' => 't_easy',
            'abbreviation' => 'EASY',
            'language' => 'english',
            'info_text' => 'EasyEnglish Bible 2018 (EASY)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/2079-easy-easyenglish-bible-2018',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/2079/jhn.1.easy',
        ],
        47 => [
            'table' => 't_drc1752',
            'abbreviation' => 'DRC1752',
            'language' => 'english',
            'info_text' => 'Douay-Rheims Challoner Revision 1752 (DRC1752)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/55-drc1752-douay-rheims-challoner-revision-1752',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/55/jhn.1.drc1752',
        ],
        48 => [
            'table' => 't_darby',
            'abbreviation' => 'DARBY',
            'language' => 'english',
            'info_text' => 'Darby\'s Translation 1890 (DARBY)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/478-darby-darbys-translation-1890',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/478/jhn.1.darby',
        ],
        49 => [
            'table' => 't_csb',
            'abbreviation' => 'CSB',
            'language' => 'english',
            'info_text' => 'Christian Standard Bible (CSB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1713-csb-christian-standard-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1713/jhn.1.csb',
        ],
        50 => [
            'table' => 't_cpdv',
            'abbreviation' => 'CPDV',
            'language' => 'english',
            'info_text' => 'Catholic Public Domain Version (CPDV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/42-cpdv-catholic-public-domain-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/42/jhn.1.cpdv',
        ],
        51 => [
            'table' => 't_cjb',
            'abbreviation' => 'CJB',
            'language' => 'english',
            'info_text' => 'Complete Jewish Bible (CJB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1275-cjb-complete-jewish-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1275/jhn.1.cjb',
        ],
        52 => [
            'table' => 't_cevuk',
            'abbreviation' => 'CEVUK',
            'language' => 'english',
            'info_text' => 'Contemporary English Version (Anglicised) 2012 (CEVUK)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/294-cevuk-contemporary-english-version-anglicised-2012',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/294/jhn.1.cevuk',
        ],
        53 => [
            'table' => 't_cevdc',
            'abbreviation' => 'CEVDC',
            'language' => 'english',
            'info_text' => 'Contemporary English Version (CEVDC)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/303-cevdc-contemporary-english-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/303/jhn.1.cevdc',
        ],
        54 => [
            'table' => 't_cev',
            'abbreviation' => 'CEV',
            'language' => 'english',
            'info_text' => 'Contemporary English Version (CEV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/392-cev-contemporary-english-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/392/jhn.1.cev',
        ],
        55 => [
            'table' => 't_ceb',
            'abbreviation' => 'CEB',
            'language' => 'english',
            'info_text' => 'Common English Bible (CEB)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/37-ceb-common-english-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/37/jhn.1.ceb',
        ],
        56 => [
            'table' => 't_books',
            'abbreviation' => 'BOOKS',
            'language' => 'english',
            'info_text' => 'The Books of the Bible NT (BOOKS)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/31-books-the-books-of-the-bible-nt',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/31/jhn.1.books',
        ],
        57 => [
            'table' => 't_asv',
            'abbreviation' => 'ASV',
            'language' => 'english',
            'info_text' => 'American Standard Version (ASV)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/12-asv-american-standard-version',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/12/jhn.1.asv',
        ],
        58 => [
            'table' => 't_ampc',
            'abbreviation' => 'AMPC',
            'language' => 'english',
            'info_text' => 'Amplified Bible, Classic Edition (AMPC)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/8-ampc-amplified-bible-classic-edition',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/8/jhn.1.ampc',
        ],
        59 => [
            'table' => 't_amp',
            'abbreviation' => 'AMP',
            'language' => 'english',
            'info_text' => 'The Amplified Bible (AMP)',
            'version' => '',
            'info_url' => 'https://www.bible.com/en-GB/versions/1588-amp-the-amplified-bible',
            'publisher' => '',
            'copyright' => '',
            'copyright_info' => '',
            'firstPage' => 'https://www.bible.com/en-GB/bible/1588/jhn.1.amp',
        ],
    ];

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function welcome()
    {
        // $books = DB::table('key_english')->select('n','b')->get();
        // $versions = DB::table('bible_version_key')->select()->get();
        reset($this->books);
        $bookId = key($this->books);
        reset($this->versions);
        $versionId = key($this->versions);
        $versionId = 1047;

        return view('welcome', [
            'books' => $this->books, 
            'versions' => $this->versions,
            'versionId' => $versionId,
            'bookId' => $bookId,
            'dataFromTable' => null
        ]);
    }

    public function welcomeNextPage(Request $request, $bookId, $versionId) {
        
        $table = $this->versionIdsToTable[$versionId];
        // $books = DB::table('key_english')->select('n','b')->get();
        $hasTable = Schema::hasTable($table);
        $dataFromTable = [];
        if ($hasTable) {
            $dataFromTable = DB::table('t_gw')
                ->select()
                ->inRandomOrder()
                ->limit(20)
                // ->where('b','=',$bookId)
                // ->where('v','=',$versionId)
                ->get();
        }
        // dd($dataFromTable);

        return view('welcome', [
            'books'=> $this->books, 
            'versions'=> $this->versions,
            'bookId' => $bookId,
            'versionId' => $versionId,
            'dataFromTable' => $dataFromTable
        ]);
    }
}
